import React from 'react'
import DormWrapper from '../../src/styledComponents/DormWrapper'
import Head from 'next/head'
import NavWrapper from '../../src/styledComponents/NavWrapper'
import MainNav from '../../src/Components/MainNav'
import Text from '../../src/styledComponents/Text'
import Button from '../../src/styledComponents/Button'
import Carousel from '../../src/Components/Carousel'
import Image from 'next/image'
import heart from '../../public/heart.png'
import share from '../../public/share.png'
import { server } from '../../config'
import { useRouter } from 'next/dist/client/router'
import AnchorLink from '../../src/Components/AnchorLink'
import ProfileCard from '../../src/Components/ProfileCard'

// Dorm page to display dorm details of the dorm 

function dorm({ data }) {

    const router = useRouter()

    const { dorm } = router.query

    const room = data[dorm]

    return (
        <DormWrapper className="room__page">
            <Head>
                <title> Perchers | Hostels and Halls </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

        {/* Dorm Navigation Bar */}
            <MainNav>
            </MainNav>

            <DormWrapper className="room" >
                <DormWrapper className="room__sub__nav" >
                    <DormWrapper className="room__sub__navigation" >
                        <DormWrapper>
                            {/* <AnchorLink route=""> */}
                            Listing
                            {/* </AnchorLink> */}
                        </DormWrapper>
                        <DormWrapper className="room__sub__navigation__arrow" >
                            {`>`}
                        </DormWrapper>
                        <DormWrapper>
                            {room.description}
                        </DormWrapper>
                    </DormWrapper>
                    <DormWrapper className="room__sub__nav__icons">
                        <DormWrapper>
                            <Button name="icon">
                                <Image
                                    src={share}
                                    layout="fill" />
                            </Button>
                        </DormWrapper>
                        <DormWrapper>
                            <Button name="icon">
                                <Image
                                    src={heart}
                                    layout="fill" />
                            </Button>
                        </DormWrapper>
                    </DormWrapper>
                </DormWrapper>
                <DormWrapper className="room__main">
                    <DormWrapper className="room__detail" >
                        <DormWrapper className="room__carousel" >
                            {/* <Carousel preview={true} /> */}
                        </DormWrapper>
                        <DormWrapper className="room__main__details" >
                            <DormWrapper className="room__detail__head" >
                                <DormWrapper >
                                    <Text className="main__head">
                                        {room.description}
                                    </Text>
                                </DormWrapper>
                                <DormWrapper>
                                    <Text className="head" >
                                        {`GH¢${room?.price}`}
                                    </Text>
                                </DormWrapper>
                            </DormWrapper>
                            <DormWrapper className="detail__btns" >
                                <AnchorLink route="/profile/chat">
                                    <Button name="offer__btn" >
                                        Make an Offer
                                    </Button>
                                </AnchorLink>
                                <Button name="secondary" >
                                    Apply
                                </Button>
                            </DormWrapper>
                            <DormWrapper className="room__description" >
                                <Text className="body__head">
                                    Detail <br />
                                </Text>
                                <Text className="body__text" >
                                    {room.detail}
                                </Text>
                            </DormWrapper>
                        </DormWrapper>
                    </DormWrapper>
                    <DormWrapper className="room__sub">
                        <ProfileCard >
                            <Button name="secondary" >
                                View Profile
                            </Button>
                        </ProfileCard>
                    </DormWrapper>
                </DormWrapper>
            </DormWrapper>

        </DormWrapper>
    )
}

// Fetches room data from api in the API folder in pages folder 
export async function getServerSideProps(context) {
    const res = await fetch(`${server}/api/rooms`)
    const data = await res.json()



    return {
        props: { data },
    }
}

export default dorm
