import React from 'react'
import DormWrapper from '../../src/styledComponents/DormWrapper'
import Head from 'next/head'
import MainNav from '../../src/Components/MainNav'
import ListCard from '../../src/Components/ListCard'
import { server } from '../../config'
import NavWrapper from '../../src/styledComponents/NavWrapper'
import Input from '../../src/styledComponents/Input'
import Image from 'next/image'
import filter from '../../public/filter.png'
import Button from '../../src/styledComponents/Button'
import Text from '../../src/styledComponents/Text'

function index(data) {



    return (
        <DormWrapper className="dorms" >
            <Head>
                <title> Perchers | Hostels and Halls </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainNav>
                <NavWrapper  >
                    <Input type="text" placeholder="Search for dorms" className="dorm__search__input" />
                </NavWrapper>
                <NavWrapper>
                    <Button name="filter">
                        <Image
                            src={filter}
                            width={'20px'}
                            height={`20px`} />
                        <Text className="filter__btn__text" >
                            Filter
                        </Text>
                    </Button>
                </NavWrapper>
            </MainNav>

            <DormWrapper className="dorms__main" >
                <DormWrapper className="dorms__head" >
                    Availabe Dormetories
                </DormWrapper>
                <DormWrapper className="dorms__render">
                    {
                        data.data.map((room, index) => (
                            <ListCard room={room} key={index} />
                        ))
                    }
                </DormWrapper>
            </DormWrapper>
        </DormWrapper>
    )
}


export async function getServerSideProps(context) {
    const res = await fetch(`${server}/api/rooms`)
    const data = await res.json()



    return {
        props: { data },
    }
}

export default index
