import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import AnchorLink from '../src/Components/AnchorLink'
import Button from '../src/styledComponents/Button'
import Form from '../src/styledComponents/Form'
import HostWrapper from '../src/styledComponents/HostWrapper'
import Input from '../src/styledComponents/Input'
import Text from '../src/styledComponents/Text'
import Check from '../src/Components/Check'
import MainNav from '../src/Components/MainNav'
import TextInput from '../src/styledComponents/TextInput'

function host() {

    const [check, setCheck] = useState(false)
    const [images, setImages] = useState(null)
    // const [image, setImage] = useState(null)

    // useEffect(() => {
    //     const imageArray = []?.push(image)
    //     console.log(imageArray)

    // }, [image])

    const allImages = []

    const handleImages = (e) => {
        const reader = new FileReader()
        reader.onload = () => {
            if (reader.readyState === 2) {
                setImages(reader.result)
            }
        }
        reader.readAsDataURL(e.target.files[0])
        reader.onerror = () => {
            console.error(reader.error)
        }
    }





    return (
        <HostWrapper className="host" >
            <Head>
                <title> Host a Room </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainNav></MainNav>
            <HostWrapper className="host__page" >
                <HostWrapper className="host__head__container" >
                    {/* <HostWrapper className="host__logo" >
                        PINQL
                    </HostWrapper> */}
                    <HostWrapper className="host__head__text" >
                        Host a room
                    </HostWrapper>
                </HostWrapper>
                <HostWrapper className="host__detail__box" >
                    <HostWrapper className="host__input__section">
                        <HostWrapper>
                            <Input type="text" placeholder="University" className="register__input" />
                        </HostWrapper>
                        <HostWrapper>
                            <Input type="text" placeholder="Hall" className="register__input" />
                        </HostWrapper>
                        <HostWrapper>
                            <Input type="text" placeholder="Room Number" className="register__input" />
                        </HostWrapper>
                    </HostWrapper>
                    <HostWrapper className="host__section">
                        <HostWrapper className="host__sub__section">
                            <Text className="host__sub__text">
                                Bed
                            </Text>
                        </HostWrapper>
                        <HostWrapper className="host__check__section" >
                            <Check>
                                Whole
                            </Check>
                            <Check>
                                Perch
                            </Check>
                        </HostWrapper>
                    </HostWrapper>
                    <HostWrapper className="host__section">
                        <HostWrapper className="host__sub__section">
                            <Text className="host__sub__text">
                                Bathroom
                            </Text>
                        </HostWrapper>
                        <HostWrapper className="host__check__section">
                            <Check>
                                In room
                            </Check>
                            <Check>
                                On Floor
                            </Check>
                        </HostWrapper>
                    </HostWrapper>
                    <HostWrapper className="host__section">
                        <HostWrapper className="host__sub__section">
                            <Text className="host__sub__text">
                                Essentials
                            </Text>
                        </HostWrapper>
                        <HostWrapper className="host__check__section">
                            <Check>
                                Fridge
                            </Check>
                            <Check>
                                Cooker
                            </Check>
                            <Check>
                                Fan
                            </Check>
                            <Check>
                                WiFi
                            </Check>
                            <Check>
                                Other
                            </Check>
                        </HostWrapper>
                    </HostWrapper>
                    <HostWrapper className="host__section">
                        <HostWrapper className="host__sub__section">
                            <Text className="host__sub__text">
                                Add image
                            </Text>
                        </HostWrapper>
                        <HostWrapper >
                            <Input type="file" multiple onChange={(e) => handleImages(e)} />
                        </HostWrapper>
                        <HostWrapper className="host__images__box" 
                        open={images ? true : false} >
                            {images ? <HostWrapper className="host__image">
                                <Image src={images} layout="fill"
                                    alt="dp" />
                            </HostWrapper> : null}
                            {/* {
                                images?.map((image, index) => (
                                    <HostWrapper key={index}>
                                        <Image src={image} layout="fill"
                                            alt="dp" />
                                    </HostWrapper>
                                ))
                            } */}
                        </HostWrapper>
                    </HostWrapper>
                    <HostWrapper className="host__section">
                        <HostWrapper className="host__sub__section">
                            <Text className="host__sub__text">
                                Add Description
                            </Text>
                        </HostWrapper>
                        <HostWrapper >
                            <TextInput type="text" placeholder="Describe your room" className="host__description__text" />
                        </HostWrapper>
                    </HostWrapper>
                    <HostWrapper className="host__section">
                        <HostWrapper className="host__sub__section">
                            <Text className="host__sub__text">
                                Price
                            </Text>
                        </HostWrapper>
                        <HostWrapper className="host__check__section">
                            <HostWrapper className="host__price__box" >
                                <Text className="cedi__input" >
                                    Gh₵
                                </Text>
                                <Input type="number" placeholder="Price" className="price__input" />
                            </HostWrapper>
                            <HostWrapper>
                                <Check>
                                    Negotiable
                                </Check>
                            </HostWrapper>
                        </HostWrapper>

                    </HostWrapper>
                    <HostWrapper className="host__section__btn">
                        <Button name="primary expand" >
                            Submit Room
                        </Button>
                    </HostWrapper>
                </HostWrapper>
            </HostWrapper>
        </HostWrapper>
    )
}

export default host
