import Head from 'next/head'
import Image from 'next/image'
import HomeNav from '../src/Components/HomeNav'
import Button from '../src/styledComponents/Button'
import HomeWrapper from '../src/styledComponents/HomeWrapper'
import Input from '../src/styledComponents/Input'
import Main from '../src/styledComponents/Main'
import bg from '../public/pic.jpg'
import { useState } from 'react'
import Text from '../src/styledComponents/Text'
import AnchorLink from '../src/Components/AnchorLink'
import Select from '../src/styledComponents/Select'
import Option from '../src/styledComponents/Option'


export default function Home() {

  const [sectionSelect, setSectionSelect] = useState(true)

  return (
    <HomeWrapper className="home" >
      <Head>
        <title>PINQL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation component  */}
      <HomeNav />

      {/* Main Property of the landing page  */}

      <Main className="main" >
        <HomeWrapper className="home__main" >
          <HomeWrapper className="home__main__section__btn" >
            <HomeWrapper
              className="home__section__select"
              select={sectionSelect}
            ></HomeWrapper>
            <HomeWrapper className="home__main__section" >
              <Button
                name="section__btn petch__btn"
                click={() => setSectionSelect(true)}
                select={sectionSelect}
              >
                Petch
              </Button>
              <Button
                name="host__btn section__btn"
                click={() => setSectionSelect(false)}
                select={sectionSelect}
              >
                Host
              </Button>
            </HomeWrapper>
          </HomeWrapper>
          <HomeWrapper className="home__main__text" >
            {
              sectionSelect ? (
                <HomeWrapper className="home__main__text" >
                  <Text className="home__head__text" >
                    Find halls and amazing <br /> roomies to Petch.
                  </Text>
                </HomeWrapper>

              ) : (
                <HomeWrapper className="home__main__text" >
                  <Text className="home__head__text" >
                    Host your rooms <br /> get cool roomies.
                  </Text>
                </HomeWrapper>
              )
            }
          </HomeWrapper>
          <HomeWrapper className="home__main__search" >
            <HomeWrapper className="home__uni__search" >
              {/* <HomeWrapper className="uni__search"> */}
              {/* <Input type='text' placeholder="University" className="uni__search__input" /> */}
              <Select required>
                <Option value="Univerity Of Ghana, Legon">
                  Univerity of Ghana, Legon
                </Option>
                <Option value="KNUST" >
                  KNUST
                </Option>
                <Option value="UCC" >
                  UCC
                </Option>
                <Option value="University of Winneba" >
                  University of Winneba
                </Option>
              </Select>
              {/* </HomeWrapper> */}
              <AnchorLink route="/dorms">
                <Button name="primary" >
                  Search
                </Button>
              </AnchorLink>
            </HomeWrapper>
            <HomeWrapper className="home__check__date" >
              <HomeWrapper>
                In
                <Input type="date" placeholder="Check In" className="date__input" />
              </HomeWrapper>
              <HomeWrapper>
                Out
                <Input type="date" placeholder="Check In" className="date__input" />
              </HomeWrapper>
            </HomeWrapper>
          </HomeWrapper>
        </HomeWrapper>
        <HomeWrapper className="home__main__image" >
          <HomeWrapper className="home__image__container" image={bg} >
            {/* <Image src={bg}
              // width={100}
              // height={100}
              layout="fill"
              alt="dp" /> */}
          </HomeWrapper>
        </HomeWrapper>
      </Main>

    </HomeWrapper>
  )
}
