import React, { useState } from 'react'
import SignIn from '../src/Components/SignIn'
import SignUp from '../src/Components/SignUp'
import Button from '../src/styledComponents/Button'
import RegisWrapper from '../src/styledComponents/RegisWrapper'
import Head from 'next/head'

function registration() {

    const [register, setRegister] = useState(true)


    return (
        <RegisWrapper className="registration" >
            <Head>
                <title>
                    {
                        register ? 'Sign Up' : "Sign In"
                    }
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <RegisWrapper className="registration__pic" >
                picture
            </RegisWrapper>
            <RegisWrapper className="registration__main" >
                <RegisWrapper className="registration__logo" >
                    PINQL
                </RegisWrapper>
                <RegisWrapper register={register} className="registration__section" >
                    <RegisWrapper className="registration__tab" >
                        <Button
                            click={() => setRegister(false)} 
                            name="sign__tab__btn sign__in__tab__select"
                            select={register}
                            >
                            Sign In 
                        </Button>
                        <Button
                            click={() => setRegister(true)}
                            name="sign__tab__btn sign__up__tab__select"
                            select={register}
                            >
                            Sign Up
                        </Button>
                    </RegisWrapper>
                    <RegisWrapper className="registration__render">
                        {
                            register ? <SignUp /> : <SignIn />
                        }
                    </RegisWrapper>
                </RegisWrapper>
            </RegisWrapper>
        </RegisWrapper>
    )
}

export default registration
