import React, { useEffect, useState } from 'react'
import SignIn from '../src/Components/SignIn'
import SignUp from '../src/Components/SignUp'
import Button from '../src/styledComponents/Button'
import RegisWrapper from '../src/styledComponents/RegisWrapper'
import Head from 'next/head'
import { getSession } from 'next-auth/react'


// Registration Page containg the Sign Up and Sign In 

function Registration() {

    // Set state for Sign In and Sign Up Tab
    const [register, setRegister] = useState(false)

    // Get query set from router 
    // const { registerValue } = router.query

    // useEffect(() => {
    //     if (registerValue === 'true') {
    //         setRegister(false)
    //     } else {
    //         setRegister(true)
    //     }
    //     console.log(registerValue)
    // }, [register])


    return (
        <RegisWrapper className="registration" >
            <Head>
                <title>
                    {
                        register ? 'Sign Up' : "Sign In"
                    }
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <RegisWrapper className="registration__pic" >
                picture
            </RegisWrapper>
            <RegisWrapper className="registration__main" >
                <RegisWrapper className="registration__logo" >
                    PINQL
                </RegisWrapper>
                {/* This Section Invokes the function that toggles the register  */}
                <RegisWrapper register={register} className="registration__section" >
                    <RegisWrapper className="registration__tab" >
                        <Button
                            click={() => setRegister(false)}
                            name="sign__tab__btn sign__in__tab__select"
                            select={register}
                        >
                            Sign In
                        </Button>
                        <Button
                            click={() => setRegister(true)}
                            name="sign__tab__btn sign__up__tab__select"
                            select={register}
                        >
                            Sign Up
                        </Button>
                    </RegisWrapper>
                    {/* This section display the sign Up or SIgn In depending on the one toggled  */}
                    <RegisWrapper className="registration__render">
                        {
                            register ? <SignUp /> : <SignIn />
                        }
                    </RegisWrapper>
                </RegisWrapper>
            </RegisWrapper>
        </RegisWrapper>
    )
}

export async function getServerSideProps(context) {
    const session = await getSession(context)

    if (session) {
        return {
            redirect: {
                destination: '/dorms',
                permanent: false
            }
        }
    }

    return {
        props: { session }
    }
}

export default Registration
