import React, { useContext, useEffect, useState } from 'react'
import SignIn from '../src/Components/SignIn'
import SignUp from '../src/Components/SignUp'
import Button from '../src/styledComponents/Button'
import RegisWrapper from '../src/styledComponents/RegisWrapper'
import Head from 'next/head'
import { RegisterContext } from '../src/Components/Context'

// Registration Page containg the Sign Up and Sign In 

function registration() {

    // uses Context to Toggle between Sign Up and SIgn In 
    const [register, setregister] = useContext(RegisterContext)

    // State to get sign Up and Sign In details 
    const [signUpDetails, setSignUpDetail] = useState(null)
    const [signInDetails, setSignInDetail] = useState(null)

    // Displays sign Up and sign In details in console 
    useEffect(() => {
        console.log('sign In' ,signInDetails)
    }, [signInDetails])

    useEffect(() => {
        console.log('sign Up' ,signUpDetails)
    }, [signUpDetails])


    return (
        <RegisWrapper className="registration" >
            <Head>
                <title>
                    {
                        register ? 'Sign Up' : "Sign In"
                    }
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <RegisWrapper className="registration__pic" >
                picture
            </RegisWrapper>
            <RegisWrapper className="registration__main" >
                <RegisWrapper className="registration__logo" >
                    PINQL
                </RegisWrapper>
                {/* This Section Invokes the function that toggles the register  */}
                <RegisWrapper register={register} className="registration__section" >
                    <RegisWrapper className="registration__tab" >
                        <Button
                            click={() => setregister(false)} 
                            name="sign__tab__btn sign__in__tab__select"
                            select={register}
                            >
                            Sign In 
                        </Button>
                        <Button
                            click={() => setregister(true)}
                            name="sign__tab__btn sign__up__tab__select"
                            select={register}
                            >
                            Sign Up
                        </Button>
                    </RegisWrapper>
                    {/* This section display the sign Up or SIgn In depending on the one toggled  */}
                    <RegisWrapper className="registration__render">
                        {
                            register ? <SignUp setSignUpDetail={setSignUpDetail} /> : <SignIn setSignInDetail={setSignInDetail} />
                        }
                    </RegisWrapper>
                </RegisWrapper>
            </RegisWrapper>
        </RegisWrapper>
    )
}

export default registration
